"""Kernel-enforced write isolation for clone-local scientific workers.

Landlock confines every worker's writes to this checkout's declared mutable
roots while leaving reads and executable loading unrestricted.
"""

from __future__ import annotations

import ctypes
import hashlib
import os
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Final

LOCAL_WRITE_ROOTS_ENV: Final = "EASYDESIGN_LOCAL_WRITE_ROOTS"

_LANDLOCK_CREATE_RULESET = 444
_LANDLOCK_ADD_RULE = 445
_LANDLOCK_RESTRICT_SELF = 446
_LANDLOCK_CREATE_RULESET_VERSION = 1
_LANDLOCK_RULE_PATH_BENEATH = 1
_PR_SET_NO_NEW_PRIVS = 38

_WRITE_FILE = 1 << 1
_REMOVE_DIR = 1 << 4
_REMOVE_FILE = 1 << 5
_MAKE_CHAR = 1 << 6
_MAKE_DIR = 1 << 7
_MAKE_REG = 1 << 8
_MAKE_SOCK = 1 << 9
_MAKE_FIFO = 1 << 10
_MAKE_BLOCK = 1 << 11
_MAKE_SYM = 1 << 12
_HANDLED_WRITES = (
    _WRITE_FILE
    | _REMOVE_DIR
    | _REMOVE_FILE
    | _MAKE_CHAR
    | _MAKE_DIR
    | _MAKE_REG
    | _MAKE_SOCK
    | _MAKE_FIFO
    | _MAKE_BLOCK
    | _MAKE_SYM
)


class _RulesetAttr(ctypes.Structure):
    _fields_ = [("handled_access_fs", ctypes.c_uint64)]


class _PathBeneathAttr(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ("allowed_access", ctypes.c_uint64),
        ("parent_fd", ctypes.c_int32),
    ]


def _syscall(libc: ctypes.CDLL, number: int, *arguments: object) -> int:
    ctypes.set_errno(0)
    result = int(libc.syscall(number, *arguments))
    if result < 0:
        error = ctypes.get_errno()
        raise OSError(error, os.strerror(error))
    return result


def landlock_abi_version() -> int:
    """Return the host Landlock ABI version, or raise when unavailable."""

    if not sys.platform.startswith("linux"):
        raise OSError("local-worker write isolation requires Linux Landlock")
    libc = ctypes.CDLL(None, use_errno=True)
    return _syscall(
        libc,
        _LANDLOCK_CREATE_RULESET,
        0,
        0,
        _LANDLOCK_CREATE_RULESET_VERSION,
    )


def apply_local_write_sandbox(writable_roots: Sequence[Path]) -> int:
    """Deny writes outside local roots plus required kernel device interfaces."""

    abi = landlock_abi_version()
    if abi < 1:
        raise OSError(f"Landlock ABI 1+ required, host reported {abi}")
    roots = tuple(dict.fromkeys(path.resolve(strict=True) for path in writable_roots))
    if not roots:
        raise OSError("write sandbox requires at least one writable root")

    libc = ctypes.CDLL(None, use_errno=True)
    ruleset = _RulesetAttr(handled_access_fs=_HANDLED_WRITES)
    ruleset_fd = _syscall(
        libc,
        _LANDLOCK_CREATE_RULESET,
        ctypes.byref(ruleset),
        ctypes.sizeof(ruleset),
        0,
    )
    try:
        open_path = getattr(os, "O_PATH", os.O_RDONLY)
        # CUDA needs writable device nodes and per-process procfs controls.
        # Neither tree contains EasyDesign environments, models, caches, or jobs.
        for root in (*roots, Path("/dev"), Path("/proc")):
            parent_fd = os.open(root, open_path | os.O_CLOEXEC)
            try:
                rule = _PathBeneathAttr(
                    allowed_access=_HANDLED_WRITES,
                    parent_fd=parent_fd,
                )
                _syscall(
                    libc,
                    _LANDLOCK_ADD_RULE,
                    ruleset_fd,
                    _LANDLOCK_RULE_PATH_BENEATH,
                    ctypes.byref(rule),
                    0,
                )
            finally:
                os.close(parent_fd)
        ctypes.set_errno(0)
        if libc.prctl(_PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) != 0:
            error = ctypes.get_errno()
            raise OSError(error, os.strerror(error))
        _syscall(libc, _LANDLOCK_RESTRICT_SELF, ruleset_fd, 0)
    finally:
        os.close(ruleset_fd)
    return abi


_SITECUSTOMIZE = r'''# Generated by easydesign-local; do not edit.
import errno
import os
import shutil
import tempfile
from pathlib import Path

_write_roots = tuple(
    Path(value).resolve(strict=True)
    for value in os.environ.get("EASYDESIGN_LOCAL_WRITE_ROOTS", "").split(os.pathsep)
    if value
)
if _write_roots:
    _original_replace = os.replace

    def _inside_write_roots(path):
        candidate = Path(os.fsdecode(path)).resolve(strict=False)
        return any(candidate == root or root in candidate.parents for root in _write_roots)

    def _guarded_replace(source, destination, *, src_dir_fd=None, dst_dir_fd=None):
        try:
            return _original_replace(
                source,
                destination,
                src_dir_fd=src_dir_fd,
                dst_dir_fd=dst_dir_fd,
            )
        except OSError as error:
            if (
                error.errno != errno.EXDEV
                or src_dir_fd is not None
                or dst_dir_fd is not None
                or not _inside_write_roots(source)
                or not _inside_write_roots(destination)
                or not Path(source).is_file()
                or Path(source).is_symlink()
            ):
                raise
            target = Path(destination)
            descriptor, temporary_name = tempfile.mkstemp(
                prefix=".easydesign-replace-",
                suffix=".tmp",
                dir=target.parent,
            )
            temporary = Path(temporary_name)
            try:
                with os.fdopen(descriptor, "wb") as output, Path(source).open("rb") as input_:
                    shutil.copyfileobj(input_, output)
                    output.flush()
                    os.fsync(output.fileno())
                shutil.copymode(source, temporary, follow_symlinks=False)
                _original_replace(temporary, target)
                Path(source).unlink()
            except BaseException:
                temporary.unlink(missing_ok=True)
                raise

    os.replace = _guarded_replace
'''


def install_python_startup_guard(state_root: Path) -> Path:
    """Install an immutable startup hook that makes Python cache probes read-only."""

    digest = hashlib.sha256(_SITECUSTOMIZE.encode("utf-8")).hexdigest()[:16]
    root = state_root / "python-startup" / digest
    path = root / "sitecustomize.py"
    root.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if path.read_text(encoding="utf-8") != _SITECUSTOMIZE:
            raise OSError(f"Python startup guard identity mismatch: {path}")
    else:
        path.write_text(_SITECUSTOMIZE, encoding="utf-8")
    return root


__all__ = [
    "LOCAL_WRITE_ROOTS_ENV",
    "apply_local_write_sandbox",
    "install_python_startup_guard",
    "landlock_abi_version",
]
