"""Stage 06 scale-generation contracts."""

from .models import (
    ScaleBundle,
    ScaleCoverageReport,
    ScaleExecutionState,
    ScalePlan,
    ScaleProfile,
    ScaleResourceReport,
    ScaleShard,
    ScaleStrategyAuthorization,
    ScaleTaskTable,
)
from .multi_strategy import (
    ALLOCATION_POLICY,
    MultiStrategyCandidateIndex,
    MultiStrategyScaleAuthorization,
    MultiStrategyScaleShard,
    ScaleBundleV0_2,
    ScaleCoverageReportV0_2,
    ScalePlanV0_2,
    StrategyAllocation,
    StrategyScaleCoverage,
    allocate_equal_candidate_budget,
    build_multi_strategy_shards,
    scale_candidate_id,
)

__all__ = [
    "ALLOCATION_POLICY",
    "MultiStrategyCandidateIndex",
    "MultiStrategyScaleAuthorization",
    "MultiStrategyScaleShard",
    "ScaleBundle",
    "ScaleBundleV0_2",
    "ScaleCoverageReport",
    "ScaleCoverageReportV0_2",
    "ScaleExecutionState",
    "ScalePlan",
    "ScalePlanV0_2",
    "ScaleProfile",
    "ScaleResourceReport",
    "ScaleShard",
    "ScaleStrategyAuthorization",
    "ScaleTaskTable",
    "StrategyAllocation",
    "StrategyScaleCoverage",
    "allocate_equal_candidate_budget",
    "build_multi_strategy_shards",
    "scale_candidate_id",
]
