"""EasyDesign 跨阶段基础契约。"""

from .artifacts import ArtifactRef
from .attempts import Attempt, ErrorInfo, ExecutionStatus
from .claims import (
    AssertionDomain,
    ClaimEvidenceRef,
    ClaimReceipt,
    ClaimStatus,
    ClaimType,
    EvidenceKind,
)
from .decisions import (
    DecisionAuthority,
    DecisionOption,
    DecisionRecord,
    DecisionRequest,
    DecisionStatus,
)
from .errors import (
    ArtifactIntegrityError,
    ArtifactNotFoundError,
    BackendContractError,
    ConfigurationError,
    ContractError,
    EasyDesignError,
    ManifestStateError,
    PathPolicyError,
    PredictionOutputError,
    SequenceInputError,
    SerializationError,
    TargetInputError,
    UndeclaredArtifactError,
)
from .hashing import sha256_file, verify_sha256
from .identity import package_tree_sha256, resolve_code_identity
from .manifests import (
    CodeIdentity,
    CodeIdentitySource,
    EvidenceStatus,
    RunManifest,
    RuntimeProfileRef,
    StageId,
    StageManifest,
    WorkflowState,
    WorkflowStateType,
)
from .msa import (
    MsaLibraryEntry,
    MsaLibraryManifest,
    MsaLibraryProducer,
    MsaLibrarySource,
    MsaReleaseReceipt,
    MsaSourceReceipt,
    RemoteMsaChainReceipt,
    RemoteMsaReceipt,
)
from .serialization import (
    canonical_json_bytes,
    canonical_model_sha256,
    dump_model,
    load_model,
)
from .target_identity import (
    ALIGNMENT_ALGORITHM,
    ALIGNMENT_PARAMETERS,
    CanonicalIdentity,
    CanonicalIdentityStatus,
    ConstructRelationship,
    DesignResidueMapping,
    DesignScopeIdentity,
    EditType,
    ExperimentalConstructIdentity,
    MappingStatus,
    ObservedCoordinateIdentity,
    ReviewRequirement,
    TargetIdentityReport,
    resolve_target_identity,
)
from .tasks import (
    ProgressSnapshot,
    TaskAttemptRecord,
    TaskEvent,
    TaskHeartbeat,
    TaskRecord,
    TaskStatus,
)

__all__ = [
    "ALIGNMENT_ALGORITHM",
    "ALIGNMENT_PARAMETERS",
    "ArtifactIntegrityError",
    "ArtifactNotFoundError",
    "ArtifactRef",
    "Attempt",
    "AssertionDomain",
    "BackendContractError",
    "CanonicalIdentity",
    "CanonicalIdentityStatus",
    "ClaimEvidenceRef",
    "ClaimReceipt",
    "ClaimStatus",
    "ClaimType",
    "ConfigurationError",
    "ConstructRelationship",
    "CodeIdentity",
    "CodeIdentitySource",
    "ContractError",
    "DecisionAuthority",
    "DecisionOption",
    "DecisionRecord",
    "DecisionRequest",
    "DecisionStatus",
    "DesignResidueMapping",
    "DesignScopeIdentity",
    "EasyDesignError",
    "EditType",
    "ErrorInfo",
    "EvidenceStatus",
    "EvidenceKind",
    "ExperimentalConstructIdentity",
    "ExecutionStatus",
    "ManifestStateError",
    "MappingStatus",
    "MsaLibraryEntry",
    "MsaLibraryManifest",
    "MsaLibraryProducer",
    "MsaLibrarySource",
    "MsaReleaseReceipt",
    "MsaSourceReceipt",
    "ObservedCoordinateIdentity",
    "RemoteMsaChainReceipt",
    "RemoteMsaReceipt",
    "ReviewRequirement",
    "PathPolicyError",
    "PredictionOutputError",
    "ProgressSnapshot",
    "RunManifest",
    "RuntimeProfileRef",
    "SequenceInputError",
    "SerializationError",
    "StageId",
    "StageManifest",
    "WorkflowState",
    "WorkflowStateType",
    "TargetInputError",
    "TargetIdentityReport",
    "TaskAttemptRecord",
    "TaskEvent",
    "TaskHeartbeat",
    "TaskRecord",
    "TaskStatus",
    "UndeclaredArtifactError",
    "canonical_json_bytes",
    "canonical_model_sha256",
    "dump_model",
    "load_model",
    "package_tree_sha256",
    "resolve_code_identity",
    "resolve_target_identity",
    "sha256_file",
    "verify_sha256",
]
