"""GPCR-aware Stage 02 analysis without changing the generic approval contract."""

from .candidate_generation import (
    CANDIDATE_SCHEMA,
    CandidateHypothesis,
    Evidence,
    generate_candidates,
)
from .models import (
    GpcrApproachChecks,
    GpcrCandidateClassification,
    GpcrCandidateCollection,
    GpcrConfidence,
    GpcrDesignMode,
    GpcrGateStatus,
    GpcrHardGate,
    GpcrResidueReference,
    GpcrSiteAnalysis,
    GpcrSiteCandidate,
)
from .structure_context import (
    ANALYSIS_SCHEMA,
    AtomRecord,
    MembraneFrame,
    ParsedStructure,
    ResidueRecord,
    StructureAnalysisError,
    TopologyAssignment,
    TopologyMap,
    analyze_structure,
    build_chain_graph,
    derive_residue_regions,
    derive_tm_frame,
    detect_self_occlusion,
    map_gpcr_topology,
    parse_structure,
)

__all__ = [
    "ANALYSIS_SCHEMA",
    "CANDIDATE_SCHEMA",
    "AtomRecord",
    "CandidateHypothesis",
    "Evidence",
    "GpcrApproachChecks",
    "GpcrCandidateClassification",
    "GpcrCandidateCollection",
    "GpcrConfidence",
    "GpcrDesignMode",
    "GpcrGateStatus",
    "GpcrHardGate",
    "GpcrResidueReference",
    "GpcrSiteAnalysis",
    "GpcrSiteCandidate",
    "MembraneFrame",
    "ParsedStructure",
    "ResidueRecord",
    "StructureAnalysisError",
    "TopologyAssignment",
    "TopologyMap",
    "analyze_structure",
    "build_chain_graph",
    "derive_residue_regions",
    "derive_tm_frame",
    "detect_self_occlusion",
    "generate_candidates",
    "map_gpcr_topology",
    "parse_structure",
]
